### ISSUE TITLE
stop capturing keyboard

### ISSUE THREAD

**Issue by ghost** [mwmbl/mwmbl#107]
if I go here:

https://mwmbl.org/

and try to enter:

~~~
encoding/json
~~~

I expect to find:

https://pkg.go.dev/encoding/json

but instead the page eats my forward slash:

~~~
encodingjson
~~~

please stop eating the keyboard, or make it VERY simple to disable.

**Comment by daoudclarke** [comment]
Thanks, this is an annoying bug.

**Comment by helios2003** [comment]
Hello, I was going through the project and found it interesting. In this issue, I see that the engine does search for ``encoding/json``. Isn't this supposed to be expected behavior? Even the URL on the search bar shows a %2F on searching it which is the encoding for forward slash. <br>
Added a screenshot for reference.
<img width="637" alt="image" src="https://github.com/mwmbl/mwmbl/assets/100564488/d47326f4-22dd-47ed-87ba-5f37b98edb38">

**Comment by daoudclarke** [comment]
@helios2003 - you're right, thanks! This is an old issue and I guess it got fixed when I removed the feature that was causing this :flushed:
