### ISSUE TITLE
Use our new logo in appropriate places

### ISSUE THREAD

**Issue by daoudclarke** [mwmbl/mwmbl#40]
![mwmbl_test_2](https://user-images.githubusercontent.com/1283077/152555644-deafa973-217f-4811-a97b-a3881bf0a469.svg)

Some places where we can use this:
- [x] Search engine front-end
- [x] Favicon
- [x] Readme
- [x] Wiki home page
- [x] Open collective page
- [x] Github page
- [x] Extension icon

**Comment by ColinEspinas** [comment]
Just made some variants to help with the integration of this new logo.

I went ahead and used a white accent instead of letting the color transparent.
I'm open to propositions for updates.

I'll probably use this comment for future updates.

### Fully filled with white accent:
![mwmbl_logo_full](https://user-images.githubusercontent.com/30630375/152590274-2e0e8436-c748-471d-8143-d72f51321421.svg)
This is destined to be used as an avatar to avoid weird cropping by platforms (e.g. the GitHub organization logo as a weird background when using the original one). 
This also avoids the accent color to be transparent and the logo being unreadable on specific backgrounds.

### Fully filled banner with white accent:
![banner_mwmbl](https://user-images.githubusercontent.com/30630375/152590726-7f129296-b9ee-4862-9687-1e4104385ad2.svg)
This is a banner for various usages, I recommend using it at the top of the readme file.

### Rounded square with white accent:
![mwmbl_logo_white](https://user-images.githubusercontent.com/30630375/152591337-64c2b64b-f28f-41c2-9a23-9811615557c6.svg)
This is the same as the one posted above but I filled the logo with white. Use this as a logo instead of the transparent one, this will prevent issues with backgrounds.
